### ISSUE TITLE
[Question] Silme Discussion

### ISSUE THREAD

**Issue by Aareon** [cvsae/silme#1]
Do you by chance have a Discord server in which we can talk about Silmecoin? Just curious as to the future of Silme, desires for the codebase, etc.

**Comment by cvsae** [comment]
Hello, just create a telegram chanel http://t.me/Csilme

**Comment by Aareon** [comment]
@cvsae It doesn’t seem that I can speak in said channel

**Comment by Aareon** [comment]
I really think Discord would be the way to go. Mind if I create a server for us to discuss there?

**Comment by Aareon** [comment]
https://discord.gg/e7uzjTp
